DROP TABLE IF EXISTS WALLET;
DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS TRANSACTIONS;

CREATE TABLE WALLET(
    USER_ID INT,
    COMMODITY VARCHAR(20),
    AMOUNT VARCHAR(50)
);

CREATE TABLE PRICES(
    COMMODITY VARCHAR(20),
    BUYPRICE VARCHAR(50),
    SELLPRICE VARCHAR(50),
    SOURCE VARCHAR(10)
);

CREATE TABLE TRANSACTIONS(
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    ACTION VARCHAR(10),
    COMMODITY VARCHAR(20),
    COMMODITY_QTY VARCHAR(50),
    AMOUNT VARCHAR(50),
    RATE VARCHAR(50)
);