CREATE TABLE WALLET(
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    COMMODITY VARCHAR(10),
    AMOUNT VARCHAR(50)
);

CREATE TABLE PRICE(

);

CREATE TABLE TRANSACTIONS(
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    TYPE VARCHAR(1),
    COMMODITY VARCHAR(10),
    AMOUNT VARCHAR(50)
);